analyzer:
  errors:
    cast_nullable_to_non_nullable: ignore
    avoid_renaming_method_parameters: ignore
  plugins:
    - custom_lint

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_final_parameters
    - always_use_package_imports
    - annotate_overrides
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - annotate_redeclares
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_relative_lib_imports
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cast_nullable_to_non_nullable
    - collection_methods_unrelated_type
    - comment_references
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - deprecated_member_use_from_same_package
    - deprecated_consistency
    - empty_catches 
    - empty_constructor_bodies
    - empty_statements
    - eol_at_end_of_file
    - file_names
    - exhaustive_cases
    - library_prefixes
    - no_leading_underscores_for_library_prefixes
    - no_logic_in_create_state
    - prefer_contains
    - prefer_final_fields