name: zameny_flutter
description: Че по заменам?
publish_to: 'none' 
version: 1.0.3+17

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  web: ^1.1.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.3
  get_it: ^7.7.0
  intl: ^0.19.0
  talker_flutter: ^4.2.0
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  animated_list_plus: ^0.5.2
  # dotted_border: ^2.1.0
  flutter_native_splash: ^2.4.4
  # dio: ^5.4.3+1
  syncfusion_flutter_datepicker: ^25.2.4
  # pdf: ^3.10.8
  screenshot: ^3.0.0
  flutter_riverpod: ^2.6.1
  mobkit_dashed_border: ^0.0.6
  flutter_portal: ^1.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_animate: ^4.5.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flex_color_scheme: ^7.3.1
  flutter_bounceable: ^1.1.0
  flutterfall: ^1.0.5
  flutter_rustore_update: ^7.0.0
  google_fonts: ^6.2.1
  hidable: ^1.0.6
  o3d: ^3.1.0
  go_router: ^14.6.2
  share_plus: ^10.1.3
  skeletonizer: ^1.4.3
  talker_riverpod_logger: ^4.6.7
  uuid: ^4.5.1
  meta_seo: ^3.0.9

dev_dependencies:
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0

flutter_native_splash:
  android: false
  web: true
  color: "#121212"
  image: "assets/icon/whale_android.png"
  android_12:
    image: "assets/icon/whale_android.png"
    color: "#121212"
    icon_background_color: "#121212"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    
  fonts:
    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: Monospace
      fonts: 
        - asset: assets/fonts/SpaceMono-Regular.ttf


import_sorter:
  comments: false
