name: zameny_flutter
description: Че по заменам?
publish_to: 'none' 
version: 1.0.6+20

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Core
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.2.3
  flutter_bounceable: ^1.1.0
  flutter_riverpod: ^2.6.1
  supabase_flutter: ^2.8.4
  talker_flutter: ^4.2.0
  go_router: ^14.6.2
  dio: ^5.8.0+1
  get_it: ^7.7.0
  intl: ^0.20.2
  web: ^1.1.0
 
  # Firebase
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  
  # Utils
  syncfusion_flutter_xlsio: ^29.1.41
  talker_riverpod_logger: ^4.7.1
  flutter_rustore_update: ^7.0.0
  freezed_annotation: ^3.0.0
  url_launcher: ^6.2.6
  share_plus: ^10.1.3
  screenshot: ^3.0.0
  freezed: ^3.0.4
  repaint: ^0.1.1
  # pdf: ^3.10.8
  uuid: ^4.5.1
  
  # UI
  syncfusion_flutter_datepicker: ^29.1.41
  flutter_native_splash: ^2.4.4
  mobkit_dashed_border: ^0.0.6
  sliding_up_panel2: ^3.2.0+2
  animated_list_plus: ^0.5.2
  flex_color_scheme: ^8.2.0
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  # dotted_border: ^2.1.0
  flutter_portal: ^1.1.4
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  skeletonizer: ^2.0.1
  flutterfall: ^1.0.5
  hidable: ^1.0.6
  o3d: ^3.1.0
  permission_handler: ^12.0.0+1

dev_dependencies:
  test: ^1.25.15
  flutter_launcher_icons: "^0.14.3"
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter_native_splash:
  android: true
  web: false
  color: "#121212"
  image: "assets/icon/whale_android.png"
  android_12:
    image: "assets/icon/whale_android.png"
    color: "#121212"
    icon_background_color: "#121212"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/whale_android.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "path/to/image.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    
  fonts:
    - family: Ubuntu
      fonts: 
        - asset: assets/fonts/Ubuntu-Regular.ttf
    - family: Monospace
      fonts: 
        - asset: assets/fonts/SpaceMono-Regular.ttf


import_sorter:
  comments: false
